# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 11:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import notification.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaiton',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('object_id', models.CharField(max_length=20)),
                ('object_type', models.IntegerField()),
                ('status', models.IntegerField(default=notification.models.ReadingStausType(1))),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('notifiee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiee', to=settings.AUTH_USER_MODEL)),
                ('notifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
