# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import notification.models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaiton',
            name='object_title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificaiton',
            name='type',
            field=models.IntegerField(default=notification.models.NotificaitonType(1)),
        ),
    ]
