# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20170708_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaiton',
            name='object_type',
            field=models.IntegerField(default=0),
        ),
    ]
