# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('cover', models.URLField(blank=True, default='http://upload.jianshu.io/collections/images/13/IMG_3003.jpg?imageMogr2/auto-orient/strip|imageView2/1/w/240/h/240')),
            ],
        ),
    ]
