# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photos',
        ),
        migrations.AddField(
            model_name='event',
            name='object_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
