# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170626_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_author',
            new_name='author',
        ),
    ]
