# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20170626_1027'),
        ('home', '0003_auto_20170626_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photos',
            field=models.ManyToManyField(to='album.Photo'),
        ),
    ]
