# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 08:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('lasttime', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='New Album', max_length=100)),
                ('content', models.CharField(blank=True, max_length=200)),
                ('visible_status', models.IntegerField(default=1)),
                ('comment_status', models.IntegerField(default=1)),
                ('pwd', models.CharField(blank=True, max_length=100)),
                ('like_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('album_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_author', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='tag.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, max_length=100)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('albums', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='album.Album')),
            ],
        ),
    ]
