# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_author',
            new_name='author',
        ),
    ]
