# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20170702_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='desc',
            new_name='content',
        ),
    ]
