# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 08:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_type', models.IntegerField()),
                ('object_id', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('parent', models.IntegerField(default=0)),
                ('comment_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('parent_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
